### PR TITLE
FunctionReporter handling of list extraction symbols

### LINKED ISSUE #126: FunctionReporter tricked by list tags and nonstandard evaluation name collisions
If a list item has the same name as a function and it gets used with the `$` syntax, then `FunctionReporter` reporter can be tricked into thinking that the function was invoked. 

To reproduce, make a package (e.g., with `package.skeleton()` or `pkgKitten::kiten()`) with the following functions:
```
func_A <- function() {
    return('hello')
}

func_B <- function() {
    foo <- list()
    foo$func_A <- 1
    return(foo)
}
```

Running `FunctionReporter` on this package will give:
```
> myreporter$nodes
     node
1: func_A
2: func_B
> myreporter$edges
   SOURCE TARGET
1: func_A func_B
```

This occurs with both the `mvbutils::foodweb` implementation in v0.2.1 on CRAN and with the new implementation on master. 

### Update:

Also happens with nonstandard evaluation, e.g., with data.table.

Examples:
```
func_D <- function() {
    foo <- data.table::data.table(x = 'trick')
    foo[, func_A := 'treat']
}

func_E <- function() {
    foo <- data.table::data.table(func_A = 'trick')
    foo[, func_A]
}
```

Edges:
```
> myreporter$edges
   SOURCE TARGET
1: func_A func_B
2: func_A func_D
3: func_A func_E
```

When you parse:
```
> .parse_function(trickypackage::func_D)
 [1] "{"          "<-"         "foo"        "::"        
 [5] "data.table" "data.table" "\"trick\""  "["         
 [9] "foo"        ""           ":="         "func_A"    
[13] "\"treat\"" 
> .parse_function(trickypackage::func_E)
 [1] "{"          "<-"         "foo"        "::"        
 [5] "data.table" "data.table" "\"trick\""  "["         
 [9] "foo"        ""           "func_A"    
```

### PR DESCRIPTION
**Pull request by jayqi**
- Resolves #126.
    - `.parse_function` and `.parse_R6_expression` will ignore the righthand side `bar` of expressions like `foo$bar`. This means if someone names a list item the same as a function in the package namespace, `FunctionReporter` won't think references to it are calls to the same-named function.
    - Added a "Known Limitations" section to roxygen documention for `FunctionReporter` addressing non-standard evaluation, among others.
- Added unit tests for `.parse_function` and `.parse_R6_expression`
- Added a `PKGNET_SUPPRESS_BROWSER` env variable so that running the tests won't keep opening baesballstats package reports in the browser.

### CODE REVIEW

File: tests/testthat/test-FunctionReporter.R [hunk 1]
```diff
@@ -156,6 +156,57 @@ test_that("FunctionReporter rejects bad packages with an informative error", {
     }, regexp = "pkgnet could not find a package called 'w0uldNEverB33aPackageName'")
 })
 
+### NETWORK EXTRACTION HELPER FUNCTIONS
+
+test_that(".parse_function correctly parses expressions for symbols", {
```
Comment (jameslamb) [inline tests/testthat/test-FunctionReporter.R]: beautiful test

File: tests/testthat/test-FunctionReporter.R [hunk 2]
```diff
@@ -156,6 +156,57 @@ test_that("FunctionReporter rejects bad packages with an informative error", {
...
+            2+2
+        }
+        result <- pkgnet:::.parse_function(body(myfunc))
+        all(c("innerfunc1", "innerfunc2", "innerfunc3", "innerfunc4") %in% result)
+    })
+})
+
+test_that(".parse_function correctly ignores right side of list extraction", {
+    # Correctly keeps left side of $ but drops right side of $
+    expect_true({
```
Comment (jameslamb) [inline tests/testthat/test-FunctionReporter.R]: does this also need an `expect_false` checking that `$listitem` was excluded

Comment (jayqi) [reply tests/testthat/test-FunctionReporter.R]: My test condition captures both: `"myfunc" %in% result & !("listitem" %in% result)`
